#Import package

In [0]:
import pandas as pd
import numpy as np

#Load dataset

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
user_item = pd.read_csv('/content/drive/My Drive/Deadline/last_hope.csv')

In [0]:
user_item['area'].value_counts()

116    140
118    138
114    131
104    130
107    130
115    130
108    128
101    122
117    121
103    120
98     120
110    117
109    114
102    114
105    108
100    107
111    105
106    102
113     99
99      94
112     90
96      70
97      30
Name: area, dtype: int64

In [0]:
temp_matrix = user_item[['price','area','ward','rooms','list_id']]

##Preprocessing data

In [0]:
temp_matrix['price'] = temp_matrix['price'] / 10000000 # divided 10.000.000 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
temp_matrix['area'] = temp_matrix['area']*1000 # Tuning

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
temp_matrix['ward'] = temp_matrix['ward']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
temp_matrix['rooms'] = temp_matrix['rooms']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
temp_matrix.describe()

price           area         ward        rooms       list_id
count   2560.000000    2560.000000  2560.000000  2560.000000  2.560000e+03
mean     542.406243  107771.484375  9379.648828     3.177344  6.196903e+07
std      755.079626    6429.930695    98.172276     1.868633  2.498180e+06
min       50.000000   96000.000000  9217.000000     1.000000  2.837343e+07
25%      183.000000  102000.000000  9285.000000     2.000000  6.171590e+07
50%      360.000000  108000.000000  9383.000000     3.000000  6.290144e+07
75%      620.000000  114000.000000  9466.000000     4.000000  6.335863e+07
max    16500.000000  118000.000000  9531.000000    11.000000  6.345392e+07

In [0]:
filter_adstats = pd.read_csv('/content/drive/My Drive/Deadline/filter_adstats.csv')

In [0]:
count_list_id = dict(filter_adstats['adlist_id'].value_counts())

In [0]:
count_list_id

{62427094: 768,
 61138796: 645,
 61246669: 604,
 59126026: 575,
 61829658: 519,
 62650901: 514,
 62812983: 426,
 62532082: 409,
 62213512: 396,
 59915892: 387,
 62382033: 385,
 59337805: 378,
 61179139: 376,
 60407593: 369,
 60816111: 363,
 62834869: 362,
 62560115: 338,
 62505174: 323,
 62123450: 316,
 61658637: 315,
 62506609: 311,
 61262181: 310,
 60191181: 308,
 55052315: 307,
 56091929: 307,
 62695270: 300,
 61991050: 296,
 62816169: 295,
 60671719: 295,
 62156609: 293,
 59215898: 293,
 62644630: 292,
 62160326: 291,
 61916786: 287,
 60437966: 285,
 62381981: 285,
 59922328: 280,
 62263181: 279,
 62787539: 278,
 61617012: 277,
 61339828: 271,
 62575292: 270,
 62222567: 266,
 61739417: 261,
 62705290: 260,
 62600841: 260,
 60081304: 257,
 61034681: 257,
 59285823: 257,
 62736103: 257,
 58825948: 247,
 59920377: 246,
 62131063: 245,
 62037608: 244,
 62412313: 239,
 57939391: 238,
 62397857: 237,
 62748625: 235,
 62441070: 232,
 61248649: 231,
 62633860: 229,
 62565619: 229,
 6079501

In [0]:
count_list_id.keys()

dict_keys([62427094, 61138796, 61246669, 59126026, 61829658, 62650901, 62812983, 62532082, 62213512, 59915892, 62382033, 59337805, 61179139, 60407593, 60816111, 62834869, 62560115, 62505174, 62123450, 61658637, 62506609, 61262181, 60191181, 55052315, 56091929, 62695270, 61991050, 62816169, 60671719, 62156609, 59215898, 62644630, 62160326, 61916786, 60437966, 62381981, 59922328, 62263181, 62787539, 61617012, 61339828, 62575292, 62222567, 61739417, 62705290, 62600841, 60081304, 61034681, 59285823, 62736103, 58825948, 59920377, 62131063, 62037608, 62412313, 57939391, 62397857, 62748625, 62441070, 61248649, 62633860, 62565619, 60795016, 62047697, 62867708, 59610183, 56364435, 62525164, 60000292, 62976664, 62984335, 62799584, 61587633, 55891510, 62830378, 55199408, 61511084, 60224391, 61570230, 60079048, 62892515, 62853772, 61759106, 63005418, 60156436, 56005881, 62405461, 61683207, 62473788, 58789649, 62342623, 62558367, 62913740, 62558365, 53524609, 62829584, 56456075, 59520149, 61874985,

In [0]:
mean = int(np.mean(np.array(list(count_list_id.values()))))

In [0]:
median = int(np.median(np.array(list(count_list_id.values()))))

In [0]:
def counter(x):
  return count_list_id.get(x, median)

In [0]:
counter(0)

49

In [0]:
temp_matrix['count'] = temp_matrix['list_id'].apply(counter)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
temp_matrix = temp_matrix.drop(columns = ['list_id'])

In [0]:
temp_matrix

price    area    ward  rooms  count
0      120.0  115000  9520.0    3.0    120
1       64.0  115000  9521.0    2.0     69
2      460.0  116000  9496.0    3.0     38
3      130.0  102000  9475.0    3.0    147
4       88.0  116000  9494.0    2.0     31
5      640.0  112000  9313.0    5.0     17
6       66.0  115000  9521.0    3.0    100
7      148.0  114000  9244.0    2.0     52
8      435.0  117000  9503.0    6.0    147
9      152.0  115000  9511.0    4.0     21
10     890.0  113000  9316.0    5.0     49
11     665.0  102000  9472.0    4.0     19
12     485.0  112000  9313.0    3.0     43
13     140.0  115000  9514.0    8.0    105
14     365.0  103000  9454.0    4.0    117
15     650.0  109000  9297.0    2.0    103
16     950.0  102000  9472.0    4.0    180
17     960.0  106000  9382.0    8.0    167
18     335.0  114000  9243.0    2.0     45
19     172.0  102000  9475.0    3.0     49
20     270.0  102000  9472.0    2.0     25
21     166.0  102000  9475.0    3.0    155
22     205.0  107000  9233.0    3.0    146
23     860.0  106000  9381.0    4.0     67
24     660.0  105000  9367.0    4.0     62
25    1520.0  108000  9461.0    4.0    103
26      65.0  118000  9525.0    2.0     47
27    1500.0  112000  9312.0    3.0     94
28    3400.0   96000  9220.0    4.0    101
29     385.0  112000  9313.0    2.0     74
...      ...     ...     ...    ...    ...
2530   182.0  110000  9275.0    3.0     49
2531   130.0  110000  9275.0    1.0     49
2532   405.0  114000  9244.0    2.0     49
2533   610.0  109000  9286.0    4.0     49
2534   140.0  113000  9321.0    1.0     49
2535   170.0  100000  9421.0    4.0     49
2536    68.0  103000  9450.0    2.0     49
2537   150.0  111000  9327.0    1.0     49
2538  1600.0  104000  9258.0    4.0     49
2539   600.0  110000  9267.0    4.0     49
2540   186.0  107000  9229.0    3.0     49
2541   530.0  107000  9230.0    4.0     49
2542   250.0  115000  9518.0    4.0     49
2543   210.0  106000  9387.0   10.0     49
2544   490.0  118000  9525.0    4.0     49
2545   140.0  115000  9512.0    4.0     49
2546   265.0  110000  9273.0    2.0     49
2547   105.0  118000  9525.0    2.0     49
2548  1200.0  108000  9458.0    6.0     49
2549   220.0  117000  9507.0    3.0     49
2550    96.0  115000  9512.0    2.0     49
2551   550.0  112000  9302.0    4.0     49
2552   390.0  104000  9260.0    2.0     49
2553   240.0  114000  9238.0    1.0     49
2554   210.0  102000  9467.0    2.0     49
2555   130.0  109000  9289.0    1.0     49
2556  2990.0   98000  9359.0   11.0     49
2557   455.0  112000  9302.0    2.0     49
2558   160.0  112000  9302.0    1.0     49
2559   345.0  117000  9507.0    2.0     49

[2560 rows x 5 columns]

In [0]:
temp_matrix.describe()

price           area         ward        rooms        count
count   2560.000000    2560.000000  2560.000000  2560.000000  2560.000000
mean     542.406243  107771.484375  9379.648828     3.177344    62.233984
std      755.079626    6429.930695    98.172276     1.868633    59.979744
min       50.000000   96000.000000  9217.000000     1.000000     1.000000
25%      183.000000  102000.000000  9285.000000     2.000000    36.000000
50%      360.000000  108000.000000  9383.000000     3.000000    49.000000
75%      620.000000  114000.000000  9466.000000     4.000000    61.000000
max    16500.000000  118000.000000  9531.000000    11.000000   768.000000

In [0]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer()

In [0]:
temp_matrix

price    area    ward  rooms  count
0      120.0  115000  9520.0    3.0    120
1       64.0  115000  9521.0    2.0     69
2      460.0  116000  9496.0    3.0     38
3      130.0  102000  9475.0    3.0    147
4       88.0  116000  9494.0    2.0     31
5      640.0  112000  9313.0    5.0     17
6       66.0  115000  9521.0    3.0    100
7      148.0  114000  9244.0    2.0     52
8      435.0  117000  9503.0    6.0    147
9      152.0  115000  9511.0    4.0     21
10     890.0  113000  9316.0    5.0     49
11     665.0  102000  9472.0    4.0     19
12     485.0  112000  9313.0    3.0     43
13     140.0  115000  9514.0    8.0    105
14     365.0  103000  9454.0    4.0    117
15     650.0  109000  9297.0    2.0    103
16     950.0  102000  9472.0    4.0    180
17     960.0  106000  9382.0    8.0    167
18     335.0  114000  9243.0    2.0     45
19     172.0  102000  9475.0    3.0     49
20     270.0  102000  9472.0    2.0     25
21     166.0  102000  9475.0    3.0    155
22     205.0  107000  9233.0    3.0    146
23     860.0  106000  9381.0    4.0     67
24     660.0  105000  9367.0    4.0     62
25    1520.0  108000  9461.0    4.0    103
26      65.0  118000  9525.0    2.0     47
27    1500.0  112000  9312.0    3.0     94
28    3400.0   96000  9220.0    4.0    101
29     385.0  112000  9313.0    2.0     74
...      ...     ...     ...    ...    ...
2530   182.0  110000  9275.0    3.0     49
2531   130.0  110000  9275.0    1.0     49
2532   405.0  114000  9244.0    2.0     49
2533   610.0  109000  9286.0    4.0     49
2534   140.0  113000  9321.0    1.0     49
2535   170.0  100000  9421.0    4.0     49
2536    68.0  103000  9450.0    2.0     49
2537   150.0  111000  9327.0    1.0     49
2538  1600.0  104000  9258.0    4.0     49
2539   600.0  110000  9267.0    4.0     49
2540   186.0  107000  9229.0    3.0     49
2541   530.0  107000  9230.0    4.0     49
2542   250.0  115000  9518.0    4.0     49
2543   210.0  106000  9387.0   10.0     49
2544   490.0  118000  9525.0    4.0     49
2545   140.0  115000  9512.0    4.0     49
2546   265.0  110000  9273.0    2.0     49
2547   105.0  118000  9525.0    2.0     49
2548  1200.0  108000  9458.0    6.0     49
2549   220.0  117000  9507.0    3.0     49
2550    96.0  115000  9512.0    2.0     49
2551   550.0  112000  9302.0    4.0     49
2552   390.0  104000  9260.0    2.0     49
2553   240.0  114000  9238.0    1.0     49
2554   210.0  102000  9467.0    2.0     49
2555   130.0  109000  9289.0    1.0     49
2556  2990.0   98000  9359.0   11.0     49
2557   455.0  112000  9302.0    2.0     49
2558   160.0  112000  9302.0    1.0     49
2559   345.0  117000  9507.0    2.0     49

[2560 rows x 5 columns]

In [0]:
processing_data = normalizer.fit_transform(temp_matrix)

In [0]:
processing_data

array([[1.03992000e-03, 9.96589953e-01, 8.25003161e-02, 2.59980000e-05,
        1.03992000e-03],
       [5.54624000e-04, 9.96589987e-01, 8.25089849e-02, 1.73320000e-05,
        5.97954000e-04],
       [3.95226530e-03, 9.96658211e-01, 8.15885032e-02, 2.57756000e-05,
        3.26491500e-04],
       ...,
       [4.04852720e-03, 9.96560531e-01, 8.27679112e-02, 1.77957000e-05,
        4.35995200e-04],
       [1.42366810e-03, 9.96567688e-01, 8.27685057e-02, 8.89790000e-06,
        4.35998400e-04],
       [2.93901830e-03, 9.96710565e-01, 8.09891225e-02, 1.70378000e-05,
        4.17425800e-04]])

In [0]:
normalizer.fit_transform(temp_matrix[:10])

array([[1.03991995e-03, 9.96589953e-01, 8.25003161e-02, 2.59979988e-05,
        1.03991995e-03],
       [5.54623993e-04, 9.96589987e-01, 8.25089849e-02, 1.73319998e-05,
        5.97953992e-04],
       [3.95226532e-03, 9.96658210e-01, 8.15885032e-02, 2.57756434e-05,
        3.26491483e-04],
       [1.26904397e-03, 9.95711419e-01, 9.24937813e-02, 2.92856300e-05,
        1.43499587e-03],
       [7.56092302e-04, 9.96667125e-01, 8.15720490e-02, 1.71839159e-05,
        2.66350697e-04],
       [5.69454025e-03, 9.96544544e-01, 8.28644584e-02, 4.44885957e-05,
        1.51261225e-04],
       [5.71955874e-04, 9.96589781e-01, 8.25089679e-02, 2.59979943e-05,
        8.66599809e-04],
       [1.29399721e-03, 9.96727577e-01, 8.08223660e-02, 1.74864487e-05,
        4.54647667e-04],
       [3.70571696e-03, 9.96710080e-01, 8.09550076e-02, 5.11133374e-05,
        1.25227677e-03],
       [1.31724067e-03, 9.96596559e-01, 8.24228685e-02, 3.46642281e-05,
        1.81987198e-04]])

In [0]:
processing_data = normalizer.fit_transform(temp_matrix)

In [0]:
processing_data = np.round(processing_data, 10)

In [0]:
processing_data

array([[1.03992000e-03, 9.96589953e-01, 8.25003161e-02, 2.59980000e-05,
        1.03992000e-03],
       [5.54624000e-04, 9.96589987e-01, 8.25089849e-02, 1.73320000e-05,
        5.97954000e-04],
       [3.95226530e-03, 9.96658211e-01, 8.15885032e-02, 2.57756000e-05,
        3.26491500e-04],
       ...,
       [4.04852720e-03, 9.96560531e-01, 8.27679112e-02, 1.77957000e-05,
        4.35995200e-04],
       [1.42366810e-03, 9.96567688e-01, 8.27685057e-02, 8.89790000e-06,
        4.35998400e-04],
       [2.93901830e-03, 9.96710565e-01, 8.09891225e-02, 1.70378000e-05,
        4.17425800e-04]])

In [0]:
def get_col(arr, col):
  return np.array([x[col] for x in arr])

In [0]:
get_col(processing_data, 0)

array([0.00103992, 0.00055462, 0.00395227, ..., 0.00404853, 0.00142367,
       0.00293902])

#Model

In [0]:
from sklearn.neighbors import NearestNeighbors

In [0]:
nbrs = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=20, n_jobs=-1).fit(processing_data)

In [0]:
type(processing_data)

numpy.ndarray

In [0]:
distance, indices = nbrs.kneighbors(processing_data)

In [0]:
len(indices)

2560

In [0]:
len(indices[0])

20

In [0]:
len(distance)

2560

In [0]:
indices

array([[   0, 1215,   13, ...,  988,  338,  400],
       [   1, 1386, 1233, ..., 2029, 1856, 2170],
       [   2, 1712, 1188, ...,  418, 1131, 1163],
       ...,
       [2557, 2443, 2150, ...,  566, 1192,  555],
       [2558,  914, 2362, ...,  128, 2270, 1313],
       [2559,  616,  404, ..., 1872,  474,  225]])

In [0]:
processing_data[585]

array([1.03991820e-03, 9.96588264e-01, 8.25261743e-02, 2.59980000e-05,
       4.24633300e-04])

In [0]:
user_item.iloc[0]

Unnamed: 0                                                                 0
Unnamed: 0.1                                                            2393
Unnamed: 0.1.1                                                          2393
account_id                                                             70040
account_name                                      Le phuong trang hung cuong
account_oid                                 0878857dd9817854a83a24c572ad90a6
ad_features                                                              NaN
ad_id                                                               43513357
area                                                                     115
area_name                                                   Huyện Bình Chánh
area_v2                                                                13115
avatar                     https://st.chotot.com/imaginary/03bb1f48898193...
body                       Nhà bán ngay chợ,Hưng Long,5x18.) đừơng trước ...

In [0]:
for index in range(20):
  print(user_item[['price','price_string','area','ward','rooms']].iloc[indices[0][index]])

price                   1.2e+09
price_string    1.200.000.000 đ
area                        115
ward                       9520
rooms                         3
Name: 0, dtype: object
price                  1.19e+09
price_string    1.190.000.000 đ
area                        115
ward                       9512
rooms                         2
Name: 1215, dtype: object
price                   1.4e+09
price_string    1.400.000.000 đ
area                        115
ward                       9514
rooms                         8
Name: 13, dtype: object
price                8.68e+08
price_string    868.000.000 đ
area                      115
ward                     9512
rooms                       1
Name: 793, dtype: object
price                  1.38e+09
price_string    1.380.000.000 đ
area                        113
ward                       9314
rooms                         1
Name: 366, dtype: object
price                  1.25e+09
price_string    1.250.000.000 đ
area                   

In [0]:
from sklearn.externals import joblib 

In [0]:
cd /content/drive/My Drive/Deadline

/content/drive/My Drive/Deadline


In [0]:
# Save the model as a pickle in a file 
joblib.dump(nbrs, 'recommendation.pkl')

['recommendation.pkl']